import {Datamock} from './data-mock';

export const DATA: Datamock[] = [
  {name: 'quang', own: 'SYS', career:'DOCTOR'},
  {name: 'minh', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'hong', own: 'SYS', career:'nurse'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'ha', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'pharmar'},
  {name: 'tin', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'anh', own: 'SYS', career:'boss'},
  {name: 'fahashi', own: 'SYS', career:'DOCTOR'},
  {name: 'quang', own: 'SYS', career:'DOCTOR'},
  {name: 'minh', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'hong', own: 'SYS', career:'nurse'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'ha', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'pharmar'},
  {name: 'tin', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'anh', own: 'SYS', career:'boss'},
  {name: 'fahashi', own: 'SYS', career:'DOCTOR'},
  {name: 'quang', own: 'SYS', career:'DOCTOR'},
  {name: 'minh', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'hong', own: 'SYS', career:'nurse'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'ha', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'pharmar'},
  {name: 'tin', own: 'SYS', career:'DOCTOR'},
  {name: 'nam', own: 'SYS', career:'DOCTOR'},
  {name: 'anh', own: 'SYS', career:'boss'},
  {name: 'fahashi', own: 'SYS', career:'DOCTOR'},
  {name: 'fahashi', own: 'SYS', career:'DOCTOR'},
  {name: 'quang', own: 'SYS', career:'DOCTOR'},
]
